In [9]:
#Explorando leitura de dados com pandas, lendo de uma API

#Importando pandas
import pandas as pd

#Criando a variável df_selic para armazenar o dataframe, e solicitando a leitura
#dos dados por API, com o método JSON.

df_selic = pd.read_json("https://api.bcb.gov.br/dados/serie/bcdata.sgs.11/dados?formato=json&dataInicial=11/04/2025")
#Tive que adicionar data inicial por solicitação da API

#Imprimindo o DF e o info()
print(df_selic)
print(df_selic.info())

           data     valor
0    11/04/2025  0.052531
1    14/04/2025  0.052531
2    15/04/2025  0.052531
3    16/04/2025  0.052531
4    17/04/2025  0.052531
..          ...       ...
246  06/04/2026  0.054266
247  07/04/2026  0.054266
248  08/04/2026  0.054266
249  09/04/2026  0.054266
250  10/04/2026  0.054266

[251 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   data    251 non-null    object
 1   valor   251 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.1+ KB
None

In [10]:
#Para verificar duplicidadede linhas (MUITO IMPORTANTE), podemos utilizar a
#função drop_duplicates()

df_selic.drop_duplicates(keep="last", inplace=True)
#Keep = last para manter o último registro
#Através do parâmetro inplace=True, faz com que a transformaçao seja salva no DF.

#No caso, não existem linhas duplicadas

print(df_selic)

           data     valor
0    11/04/2025  0.052531
1    14/04/2025  0.052531
2    15/04/2025  0.052531
3    16/04/2025  0.052531
4    17/04/2025  0.052531
..          ...       ...
246  06/04/2026  0.054266
247  07/04/2026  0.054266
248  08/04/2026  0.054266
249  09/04/2026  0.054266
250  10/04/2026  0.054266

[251 rows x 2 columns]

In [19]:
#Adicionando colunas no DF

#Importando datetime

from datetime import datetime as dt

#Salvando a data de hoje na variável data_extracao
data_extracao = dt.today()

#criando colunas no DF
df_selic["data_extracao"] = data_extracao
df_selic["responsavel"] = "Raphael"

#Imprimindo info e cabeca da DF.
print(df_selic.info())
df_selic.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   data           251 non-null    object
 1   valor          251 non-null    float64
 2   data_extracao  251 non-null    datetime64[us]
 3   responsavel    251 non-null    object
dtypes: datetime64[us](1), float64(1), object(2)
memory usage: 8.0+ KB
None

         data     valor              data_extracao responsavel
0  11/04/2025  0.052531 2026-04-11 15:28:28.930110     Raphael
1  14/04/2025  0.052531 2026-04-11 15:28:28.930110     Raphael
2  15/04/2025  0.052531 2026-04-11 15:28:28.930110     Raphael
3  16/04/2025  0.052531 2026-04-11 15:28:28.930110     Raphael
4  17/04/2025  0.052531 2026-04-11 15:28:28.930110     Raphael

In [ ]:
#Podemos localizar um dado individual no DF com a função loc e o indice entre
# chaves.
df_selic.loc[4]

#Também podemos fazer com mais de um, porém assim já se imprime a tabela
df_selic.loc[[0,22,75]]

          data     valor              data_extracao responsavel
0   11/04/2025  0.052531 2026-04-11 15:28:28.930110     Raphael
22  16/05/2025  0.054266 2026-04-11 15:28:28.930110     Raphael
75  31/07/2025  0.055131 2026-04-11 15:28:28.930110     Raphael

In [ ]:
#Para fazer um teste booleano contra os itens do DF

teste = df_selic["valor"] < 0.01
print(type(teste))

print(teste)

<class 'pandas.core.series.Series'>
0      False
1      False
2      False
3      False
4      False
       ...
246    False
247    False
248    False
249    False
250    False
Name: valor, Length: 251, dtype: bool